<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAM.Analytical">
      <HintPath>..\..\..\SAM\build\SAM.Analytical.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry">
      <HintPath>..\..\..\SAM\build\SAM.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry.Rhino, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\SAM\build\SAM.Geometry.Rhino.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RhinoCommon">
      <Version>8.19.25132.1001</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.6.1</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>6.1.2</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SAM_Solver\SAM.Analytical.Solver\SAM.Analytical.Solver.csproj" />
  </ItemGroup>
</Project>