<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Version>1.0</Version>
    <Title>SAM.Analytical.Rhino.Solver.Plugin</Title>
    <Description>Description of SAM.Analytical.Rhino.Solver.Plugin</Description>
    <TargetExt>.rhp</TargetExt>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="RhinoCommon" Version="7.4.21078.1001" IncludeAssets="compile;build" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="SAM.Analytical">
      <HintPath>..\..\..\..\SAM\build\SAM.Analytical.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry">
      <HintPath>..\..\..\..\SAM\build\SAM.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry.Rhino">
      <HintPath>..\..\..\..\SAM\build\SAM.Geometry.Rhino.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Math">
      <HintPath>..\..\..\..\SAM\build\SAM.Math.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Query\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\SAM_Solver\SAM.Analytical.Solver\SAM.Analytical.Solver.csproj" />
  </ItemGroup>
  
  <PropertyGroup Condition="$(Configuration) == 'Debug' AND $([MSBuild]::IsOSPlatform(Windows))">
    <StartProgram>C:\Program Files\Rhino 7\System\Rhino.exe</StartProgram>
    <StartArguments></StartArguments>
    <StartAction>Program</StartAction>
  </PropertyGroup>
  
</Project>